OPTIMIZATION       ?= O0
ifdef COV
COVERAGE            = -fprofile-arcs -ftest-coverage
endif
ifdef PROF
PROFILE             = -pg
endif

CXX                 = g++
INCLUDES            = -I.
CXXFLAGS            = -c \
                      -MD \
                      -std=c++11 -march=native -mtune=native \
                      -Wall -Wextra \
                      -$(OPTIMIZATION) \
                       $(COVERAGE) \
                       $(PROFILE)
LDPATH              =
LDADD               = -lgtest -lgtest_main -lpthread \
                      $(COVERAGE) \
                      $(PROFILE)
SRC                 = AllTest.cpp \
                      AnyTest.cpp \
                      AvgTest.cpp \
                      BitsRangeTest.cpp \
                      BytesRangeTest.cpp \
                      ConcatRangeTest.cpp \
                      ContainsTest.cpp \
                      CountTest.cpp \
                      DistinctRangeTest.cpp \
                      DotCallTest.cpp \
                      ElementAtTest.cpp \
                      ForeachTest.cpp \
                      GroupByRangeTest.cpp \
                      IterRangeTest.cpp \
                      LinqTest.cpp \
                      MaxTest.cpp \
                      MinTest.cpp \
                      OrderByRangeTest.cpp \
                      ReverseRangeTest.cpp \
                      SelectRangeTest.cpp \
                      SkipRangeTest.cpp \
                      SkipWhileRangeTest.cpp \
                      SumTest.cpp \
                      TakeRangeTest.cpp \
                      TakeWhileRangeTest.cpp \
                      ToDequeTest.cpp \
                      ToListTest.cpp \
                      ToSetTest.cpp \
                      ToVectorTest.cpp \
                      UnbitsRangeTest.cpp \
                      UnbytesRangeTest.cpp \
                      WhereRangeTest.cpp

OBJ                 = $(SRC:.cpp=.o)
TEST                = boolinqtest

COV_DATA            = $(shell find . -type f -name '*.d' -o -name '*.gcov' -o -name '*.gcda' -o -name '*.gcno' -o -name 'coverage' -o -name 'coverage.info')
PRO_DATA            = $(shell find . -type f -name 'gmon.out')
TMP_DATA            = $(shell find . -type f -name '*~')


all: $(TEST)


$(TEST): $(OBJ)
	$(CXX) $(OBJ) $(LDPATH) $(LDADD) -o $@


.cpp.o:
	$(CXX) $(CXXFLAGS) $(INCLUDES) $< -o $@


clean:
	rm -rf $(OBJ) $(TEST) $(TMP_DATA) $(COV_DATA) $(PRO_DATA)


coverage:
	lcov -q -c -f -b . -d . -o coverage.info &&\
	lcov -q -r coverage.info /usr/\* -b . -d . -o coverage.info &&\
	genhtml coverage.info --demangle-cpp --legend -f -q -o coverage


profile:
	gprof $(TEST) gmon.out -b -Q
